/**
 * Does the template a stranger can deploy still say what `.railway/railway.ts`
 * says (D-275)?
 *
 * The program is executed and asserted in `container.test.ts`, which is the
 * right check for what we *declare*. It cannot see what is *published*: the
 * template is regenerated by hand from a Railway project, and #31 measured
 * both halves of that going wrong — the generator carries variable names but
 * no values, so the published template came back asking a stranger for three
 * inputs with no defaults; and the template's own code changed when it was
 * published, so the draft link would have shipped a 404 button.
 *
 * Both were found by a person looking, once. This is the same look, as a
 * function, so it can be run again.
 *
 * The comparison is deliberately over **four facts**, not field-by-field:
 * Railway's published shape and the compiled graph are different formats and
 * always will be, so equality between them would be noise. These four are what
 * a person deploying actually experiences.
 */

/** The published side, as Railway's public API returns it. */
export interface PublishedTemplate {
  services: Record<
    string,
    {
      name?: string;
      source?: { repo?: string };
      variables?: Record<string, { isOptional?: boolean }>;
      volumeMounts?: Record<string, { mountPath?: string }>;
    }
  >;
}

/** The declared side, reduced from the compiled graph of `.railway/railway.ts`. */
export interface DeclaredTemplate {
  /** `owner/name`, as the program's `github()` names it. */
  repo: string;
  /** Variables a person deploying must fill in — nothing else may be required. */
  required: string[];
  /** Where the volume mounts, which is also `AGENTLINGS_HOME`. */
  mountPath: string;
}

/**
 * `owner/name`, however the repository was spelled. Railway stores a URL and
 * the program names a slug; git accepts a `.git` suffix and a trailing slash.
 * None of those is drift, and reporting them as drift would train whoever runs
 * this to ignore it.
 */
function slug(repo: string): string {
  return repo
    .trim()
    .replace(/^https?:\/\/github\.com\//i, '')
    .replace(/\.git$/i, '')
    .replace(/\/+$/, '')
    .toLowerCase();
}

/**
 * Every way the published template differs from the program, as sentences a
 * person can act on. Empty means they agree.
 *
 * A template with no service reads as a difference rather than as agreement —
 * "nothing published" and "nothing changed" must never be the same answer,
 * which is the shape of a guard that passes by never executing (D-246).
 */
export function templateDrift(
  declared: DeclaredTemplate,
  published: PublishedTemplate,
): string[] {
  const services = Object.values(published.services ?? {});
  if (services.length !== 1) {
    return [
      `the published template has ${services.length} services; an install is one service and its volume` +
        (services.length > 1 ? ` — found ${services.map((s) => s.name ?? '?').join(', ')}` : ''),
    ];
  }
  const [svc] = services;
  const drift: string[] = [];

  const publishedRepo = svc.source?.repo ?? '';
  if (slug(publishedRepo) !== slug(declared.repo)) {
    drift.push(
      `the template builds from ${publishedRepo || '(no source)'}; the program declares ${declared.repo}`,
    );
  }

  // Anything not *explicitly* optional counts as something a stranger is asked
  // for. Testing `isOptional === false` instead would let a newly-required
  // input that simply omits the flag pass unseen — which is the exact fault
  // this function exists to catch. The mutation round found that; erring
  // toward a false alarm costs a look, and erring the other way ships a
  // template that asks strangers for three things.
  const required = Object.entries(svc.variables ?? {})
    .filter(([, v]) => v.isOptional !== true)
    .map(([name]) => name)
    .sort();
  const want = [...declared.required].sort();
  if (required.join(',') !== want.join(',')) {
    drift.push(
      `a stranger is asked for ${required.length ? required.join(', ') : 'nothing'}; the program requires ${want.join(', ')}`,
    );
  }

  const mounts = Object.values(svc.volumeMounts ?? {});
  if (mounts.length !== 1) {
    drift.push(
      `the published template mounts ${mounts.length} volumes; the program mounts one at ${declared.mountPath}` +
        (mounts.length === 0
          ? ' — without it an install loses its keys, ledger and schedules on the first redeploy'
          : ''),
    );
  } else if (mounts[0].mountPath !== declared.mountPath) {
    drift.push(
      `the volume mounts at ${mounts[0].mountPath}; the program mounts it at ${declared.mountPath}, which is where the data directory is`,
    );
  }

  return drift;
}
