// The published template still says what the program says (#24, D-275).
//
//   npx tsx scripts/prove-template.mts              (from the repo root)
//   npx tsx scripts/prove-template.mts --code agentlings
//
// **No account and no credential.** Railway serves a published template to
// anyone, which is the point: this asks the platform what a *stranger* would
// be offered, and holds it against `.railway/railway.ts` executed here.
//
// It exists because the template is regenerated by hand and has drifted once
// already: #31 found it asking for three variables with no defaults, because
// the generator carries names and not values. That was caught by a person
// reading it, which is the check nobody runs twice.
//
// What it cannot do is deploy. #24's second box wants the button pressed by
// someone who is not the maintainer, and that needs a second Railway account
// on a paid plan. This proves everything short of the click.
import { readFileSync } from 'node:fs';
import { createRailwayContext, project } from 'railway/iac';
import {
  templateCodeFromReadme,
  templateDrift,
  type PublishedTemplate,
} from '../server/src/template';

const arg = (name: string): string | undefined => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
};
// The code a visitor would actually click, not a literal of our own. This
// script's default and the README's button were two separate copies of
// `agentlings`, so a republish under a new code would have had this proving
// the *old* template — green, about an artifact nobody can reach (D-030).
const README = readFileSync(new URL('../README.md', import.meta.url), 'utf8');
const CODE = arg('code') ?? templateCodeFromReadme(README);
if (!CODE) {
  // Not `process.exit()` (see the note further down) and not a silent skip: a
  // README with no button is the failure this script is for, since #31 makes
  // the button the first thing a visitor can do. Throwing stops the run with
  // a non-zero status the shell reads correctly.
  throw new Error(
    'no Deploy on Railway button in README.md — a visitor has nothing to click, so there is no published template to check',
  );
}
const API = 'https://backboard.railway.com/graphql/v2';

let pass = 0;
let fail = 0;
const ok = (label: string, cond: boolean, detail?: string): void => {
  if (cond) pass++;
  else fail++;
  console.log(`  ${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`);
};

console.log(`\nThe published template against the program (#24)\ntemplate code  ${CODE}\n`);

// ── the program, executed rather than read ───────────────────────────────────
console.log('§1  what .railway/railway.ts declares');
const authoring = await import('../.railway/railway.ts');
const graph = await authoring.default(createRailwayContext(), project);
type Compiled = {
  type: string;
  source?: { repo?: string };
  variables: Record<string, { value: { value?: string; isOptional?: boolean } }>;
  volumeAttachments?: Record<string, { mountPath: string }>;
};
const resources = graph.resources as unknown as Compiled[];
const svc = resources.find((r) => r.type === 'service');
if (!svc) throw new Error('the program declares no service');
const declared = {
  repo: svc.source?.repo ?? '',
  required: Object.entries(svc.variables)
    .filter(([, v]) => v.value.isOptional === false)
    .map(([name]) => name),
  mountPath: Object.values(svc.volumeAttachments ?? {})[0]?.mountPath ?? '',
};
ok('it names a repository', Boolean(declared.repo), declared.repo);
ok('it requires exactly one variable', declared.required.length === 1, declared.required.join(', '));
ok('it mounts one volume', Boolean(declared.mountPath), declared.mountPath);

// ── the template, as a stranger receives it ──────────────────────────────────
console.log('\n§2  what Railway hands a stranger');
const res = await fetch(API, {
  method: 'POST',
  headers: { 'content-type': 'application/json' },
  body: JSON.stringify({
    query: 'query($code:String!){ template(code:$code){ code name serializedConfig } }',
    variables: { code: CODE },
  }),
});
ok('the API answers', res.ok, `HTTP ${res.status}`);
const body = (await res.json()) as {
  data?: { template?: { name?: string; serializedConfig?: PublishedTemplate } };
};
const template = body.data?.template;
// A template that does not exist must never read as agreement. Railway's own
// dashboard returns 200 for any path, so "it loaded" proves nothing (#31);
// only the absence of a record here does.
ok('the template exists at that code', Boolean(template), template ? template.name : 'no such template');
// Never `process.exit()` here. It killed the process mid-handle on Windows —
// `Assertion failed: !(handle->flags & UV_HANDLE_CLOSING)` — and the shell
// then read the status as 0, so a run that had just printed FAIL reported
// success. A prove script whose exit code lies is worse than none.
const published = template?.serializedConfig;
if (published) {
  const svcs = Object.values(published.services ?? {});
  ok('it is one service', svcs.length === 1, svcs.map((s) => s.name ?? '?').join(', '));
  if (svcs[0]) {
    // `!== true`, matching `templateDrift`. It read `=== false` here — the
    // predicate D-276's mutation round rejected inside the function, left
    // standing in the line that prints the same fact. A newly-required input
    // that omits the flag would have been counted as drift by the verdict and
    // omitted from the detail above it, so the two lines would contradict
    // each other exactly where someone was trying to read what went wrong.
    const req = Object.entries(svcs[0].variables ?? {})
      .filter(([, v]) => v.isOptional !== true)
      .map(([n]) => n);
    console.log(`        a stranger is asked for: ${req.length ? req.join(', ') : 'nothing'}`);
    console.log(`        volume mounts at        : ${Object.values(svcs[0].volumeMounts ?? {})[0]?.mountPath ?? '(none)'}`);
    console.log(`        builds from             : ${svcs[0].source?.repo ?? '(none)'}`);
  }

  // ── the comparison ─────────────────────────────────────────────────────────
  console.log('\n§3  the two, held against each other');
  const drift = templateDrift(declared, published);
  ok('the published template is the program', drift.length === 0);
  for (const line of drift) console.log(`        · ${line}`);
}

console.log(
  `\n${pass}/${pass + fail} checks passed${fail ? ` — ${fail} FAILED` : ''}` +
    (published ? '' : ' — cannot compare without a published template'),
);
process.exitCode = fail ? 1 : 0;
